[workspace]
authors = ["Henry Institoris <xtitoris@gmail.com>"]
channels = ["conda-forge"]
name = "xtitoris-forge"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = ">=0.55.1,<0.56"

[target.win-64.dependencies]
m2-coreutils = "*"
m2-unzip = "*"
m2-tar = "*"
m2-bash = "*"
